# Matrix - Numpy

#### by Carlos Santillán


In [2]:
import numpy as np
import pandas as pd

We can cast a list with numpy:

In [7]:
list = [1, 2, 3]
c = np.asarray(list)
c

array([1, 2, 3])

We can create an ndarray in the needed size filled with ones, zeros or random values:

In [8]:
c = np.array(list)
c

array([1, 2, 3])

In [11]:
shape = (2, 2)
c = np.empty(shape)
c

array([[1.13241972e-311, 1.89145368e-307],
       [6.89796323e-307, 4.45042952e-307]])

In [13]:
d = np.ones(shape)
d

array([[1., 1.],
       [1., 1.]])

In [15]:
e = np.zeros(shape)
e

array([[0., 0.],
       [0., 0.]])

We can create an array in the shape of another array:

In [16]:
c = np.array([[1, 2], [1, 2]])
c

array([[1, 2],
       [1, 2]])

In [18]:
d = np.empty_like(c)
d

array([[-1436889632,         533],
       [          0,           0]])

Sometimes we just need to select only a part of the columns or rows in a 2d matrix:

In [19]:
a = np.asarray([[1, 1, 2, 3, 4],     ### 1st row
                [2, 6, 7, 8, 9],     ### 2nd row
                [3, 6, 7, 8, 9],     ### 3rd row
                [4, 6, 7, 8, 9],     ### 4th row
                [5, 6, 7, 8, 9]      ### 5th row
               ])

a

array([[1, 1, 2, 3, 4],
       [2, 6, 7, 8, 9],
       [3, 6, 7, 8, 9],
       [4, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

In [20]:
b = np.asarray([[1, 1], 
                [1, 1]])

b

array([[1, 1],
       [1, 1]])

SO now, we select the row in the format 'a[start:end]'

If start or end are omitted, then it means we select all range:

In [21]:
y = a[:1]     ### 1st row
y

array([[1, 1, 2, 3, 4]])

In [22]:
y = a[0:1]    ### 1st row
y

array([[1, 1, 2, 3, 4]])

In [25]:
y = a[2:5]    ### rows from 3rd to 5th
y

array([[3, 6, 7, 8, 9],
       [4, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

Notice that with this, we´re moving along the number of rows.

We can select a column in the format 'a[start:end, column_number]'

In [27]:
x = a[:, -1]    ### -1 means 1st from the end
x

array([4, 9, 9, 9, 9])

In [28]:
x = a[:, 1:3]   ### columns from 2nd to 3rd
x

array([[1, 2],
       [6, 7],
       [6, 7],
       [6, 7],
       [6, 7]])

## 2. Merge arrays

Merging Numpy arrays is not recommended because internally, Numpy will create an empty big array and the copy the contents into it.

It would be best to create the intended size at the beginning and then just fill it up. 

However, sometimes you cannot avoid merging. In this case, Numpy has some built in functions:

**Concatenate**

1d arrays:

In [44]:
a = np.array([1, 2, 3])
b = np.array([5, 6])

print(np.concatenate([a, b, b]))

[1 2 3 5 6 5 6]


2d arrays:

In [50]:
a2 = np.array([[1, 2], [3, 4]])

a2

### if axis = 0, we concatenate along rows
print(np.append(a2, b[None, :], axis = 0))

### if axis = 1, we concatenate along columns
print(np.append(a2, b[:, None], axis = 1))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


Hstack and vstack:

In [51]:
print(np.hstack([a, b]))

[1 2 3 5 6]


In [52]:
print(np.vstack([a, a]))

[[1 2 3]
 [1 2 3]]


2d arrays:

In [54]:
print(np.hstack([a2, a2]))

[[1 2 1 2]
 [3 4 3 4]]


In [55]:
print(np.vstack([a2, b]))

[[1 2]
 [3 4]
 [5 6]]


String arrays:

In [57]:
chararray = np.chararray([3, 3], itemsize = 3)

chararray[:] = 'abc'     ### pass value to all entries

print(chararray)

[[b'abc' b'abc' b'abc']
 [b'abc' b'abc' b'abc']
 [b'abc' b'abc' b'abc']]


## 3. Read/write to a file

In [58]:
a2 = np.array([
    [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1]
])

a2

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1]])

In [59]:
np.savetxt('test.txt', a2, delimiter = ",")

And we can read with 'np.loadtext()'

## 4. Sparse Matrices

In Machine Learning we can have large sparse matrices (where lots of its values are 0). 

Reading and writing this matrices is faster and the file is smaller if we use the svmlight fornat:

In [60]:
from sklearn.datasets import dump_svmlight_file, load_svmlight_file

matrix = [
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
    [1, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 1, 2],
    [1, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 1, 2]
]

labels = [1,1,1,1,1,2,2]

In [61]:
dump_svmlight_file(matrix, labels, 'svmlight.txt', zero_based = True)


In [62]:
svm_loaded = load_svmlight_file('svmlight.txt', zero_based = True)

In [63]:
svm_loaded

(<7x15 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 array([1., 1., 1., 1., 1., 2., 2.]))

We can use 'toarray()' to get the matrix back from the svmlight compressed form:

In [67]:
svm_loaded[0].toarray()     ### matrix element at index 0


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 2.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 2.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 2.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 2.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 2.],
       [1., 0., 0., 0., 0., 3., 0., 0., 0., 0., 0., 0., 0., 1., 2.],
       [1., 0., 0., 0., 0., 3., 0., 0., 0., 0., 0., 0., 0., 1., 2.]])

In [66]:
svm_loaded[1]               ### labels at index 1

array([1., 1., 1., 1., 1., 2., 2.])

# Part II - a bit of Theory

If $A \in R^{n, m}$ we say that $A$ is a matrix with $n$ rows and $m$ columns

### 1. Python Matrix

Python doesn´t have a built-in type for matrices, however, we can treat a list of lists as a matrix. For example:

In [68]:
A = [[1, 4, 5], 
     [-5, 8, 9]]

A

[[1, 4, 5], [-5, 8, 9]]

Let´s see how to work with a nested list:

In [73]:
A = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]

print("A = ", A)
print("A[1] = ", A[1])            ### 2nd row
print("A[1][2] = ", A[1][2])      ### 3rd elem. of 2nd row
print("A[0][-1] = ", A[0][-1])    ### last elem. of 1st row

column = []     ### empty list
for row in A:
    column.append(row[2])
    
print("3rd column = ", column)

A =  [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]
A[1] =  [-5, 8, 9, 0]
A[1][2] =  9
A[0][-1] =  12
3rd column =  [5, 9, 11]


Using nested lists as a matrix works for simple computational tasks, however, there is a better way of working with matrices in Python by using the Numpy package.

### 2. Numpy Array

Numpy is a package for scientific computing which has support of a powerful n-dimensional array object.

In [74]:
a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


As you can see, Numpy has a class called *ndarray*

### 3. How to create a Numpy Array?

There are several ways:

**1. Integers, floats and complex numbers**

In [75]:
A = np.array([[1, 2, 3], 
              [3, 4, 5]])

A

array([[1, 2, 3],
       [3, 4, 5]])

In [76]:
A = np.array([[1.1, 2, 3], 
              [3, 4, 5]])

A

array([[1.1, 2. , 3. ],
       [3. , 4. , 5. ]])

In [78]:
A = np.array([[1, 2, 3], 
              [3, 4, 5]], 
              dtype = complex)

A

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [3.+0.j, 4.+0.j, 5.+0.j]])

**2. Zeros and ones**

In [79]:
zeros_array = np.zeros( (2, 3) )
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [80]:
ones_array = np.ones( (1, 5), dtype = np.int32 )
print(ones_array)

[[1 1 1 1 1]]


Here we specified *dtype* as 32 bits (or 4 bytes). Hence this array can take values from $-2^{-31}$ to $2^{-31} - 1$

**3. Using arange() and shape()**

In [81]:
A = np.arange(4)
print('A = ', A)

A =  [0 1 2 3]


In [82]:
B = np.arange(12).reshape(2, 6)
print("B = ", B)

B =  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


### 4. Matrix Operations

In [83]:
A = np.array([[2, 4], 
              [5, -6]])

B = np.array([[9, -3], 
              [3, 6]])

C = A + B
print(C)

[[11  1]
 [ 8  0]]


In [85]:
D = A * B
print(D)

[[ 18 -12]
 [ 15 -36]]


Notice this method resulted in the element-wise multiplication, let´s see how to perform actual matrix multiplication:

In [87]:
A = np.array([[3, 6, 7], 
              [5, -3, 0]])

B = np.array([[1, 1], 
              [2, 1], 
              [3, -3]])

C = A.dot(B)

print(C)

[[ 36 -12]
 [ -1   2]]


In [88]:
A = np.array([[1, 1], 
              [2, 1], 
              [3, -3]])

AT = A.transpose()

print(AT)

[[ 1  2  3]
 [ 1  1 -3]]


### 5. Access Matrix elements, rows & columns

In [89]:
A = np.array([2, 4, 6, 8, 10])

print("A[0] = ", A[0])     ### 1st element
print("A[2] = ", A[2])     ### 3rd element
print("A[-1] = ", A[-1])   ### last element

A[0] =  2
A[2] =  6
A[-1] =  10


Now let´s see how to access elements of a 2d array (which is basically a matrix):

In [90]:
A = np.array([[1, 4, 5, 12],
              [-5, 8, 9, 0],
              [-6, 7, 11, 19]])

print("A[0][0] = ", A[0][0])     ### 1st element of 1st row

print("A[1][2] = ", A[1][2])     ### 3rd element 2nd row

print("A[-1][-1] = ", A[-1][-1]) ### last element of last row

A[0][0] =  1
A[1][2] =  9
A[-1][-1] =  19


**Access Rows of a matrix**

In [91]:
print("A[0] = ", A[0])     ### 1st row
print("A[2] = ", A[2])     ### 3rd row
print("A[-1] = ", A[-1])   ### last row

A[0] =  [ 1  4  5 12]
A[2] =  [-6  7 11 19]
A[-1] =  [-6  7 11 19]


**Access Columns of a matrix**

In [92]:
print("A[:, 0] = ", A[:, 0])      ### 1st column
print("A[:, 3] = ", A[:, 3])      ### 4th column
print("A[:, -1] = ", A[:, -1])    ### last column

A[:, 0] =  [ 1 -5 -6]
A[:, 3] =  [12  0 19]
A[:, -1] =  [12  0 19]


### 6. Slicing of a Matrix

In [95]:
letters = np.array([1, 3, 5, 7, 9, 7, 5])

print("3rd to 5th elements:")
print(letters[2:5])
print("\n")

print("5th from the right to the 1st")
print(letters[: -5])
print("\n")

print("6th to last element")
print(letters[5: ])
print("\n")

print("all elements")
print(letters[:])
print("\n")

print("reversed array")
print(letters[::-1])


3rd to 5th elements:
[5 7 9]


5th from the right to the 1st
[1 3]


6th to last element
[7 5]


all elements
[1 3 5 7 9 7 5]


reversed array
[5 7 9 7 5 3 1]


Now let´s see how to slice a matrix:

Remember that Python has [, ) intervals

In [107]:
A = np.array([[1, 4, 5, 12, 14], 
    [-5, 8, 9, 0, 17],
    [-6, 7, 11, 19, 21]])

print("Original matrix")
print(A)
print("\n")

print("2 rows, 4 columns")
print(A[:2, :4])
print("\n")

print("1st row, all columns")
print(A[:1, ])
print("\n")

print("all rows, 2nd column")
print(A[:, 1])
print("\n")

print("all rows, 3rd to 5th columns")
print(A[:, 2:5])

Original matrix
[[ 1  4  5 12 14]
 [-5  8  9  0 17]
 [-6  7 11 19 21]]


2 rows, 4 columns
[[ 1  4  5 12]
 [-5  8  9  0]]


1st row, all columns
[[ 1  4  5 12 14]]


all rows, 2nd column
[4 8 7]


all rows, 3rd to 5th columns
[[ 5 12 14]
 [ 9  0 17]
 [11 19 21]]
