# Python Tricks 101

#### by Carlos Santillán

## Default Block

Algunas librerías necesarias para Data Science y visualización

In [9]:
import numpy as np                  # Vectores
import pandas as pd                 # DataFrames
import matplotlib.pyplot as plt     # Gráficas
import math                         # Operaciones
import seaborn as sns               # Gráficos y controles de Scrapping
from scipy import stats             # Paquetería estadística
from scipy.stats import kstest      # Prueba de Kolmogorov-Smirnov
from scipy.stats import beta        # Distribución Beta
from scipy.stats import expon       # Distribución Exponencial

%matplotlib inline   

## Array / List Manipulation

En Python, podemos crear **listas** como sigue:

In [8]:
my_list = [1, 2, 3, 4, 5]
print(my_list)

[1, 2, 3, 4, 5]


Usando **Numpy**, podemos inicializar arreglos como sigue:
    - Necesitamos dar la dimensión del arreglo desde el inicio
    - Con un **Numpy array** podemos facilitar las operaciones entre vectores

In [11]:
my_Numpy_array = np.zeros(5)                ### initialize array with length 5

for i in range(0, len(my_Numpy_array)):     ### Fill the array
    my_Numpy_array[i] = i+1
    
my_Numpy_array                              ### Show the array

array([1., 2., 3., 4., 5.])

En Python, podemos crear **diccionarios** de datos como sigue:

In [15]:
data = {'Name':['Carlos', 'Alan', 'George', 'Héctor'],
        'Age':[27, 24, 22, 32],
        'Address':['Mexico', 'India', 'USA', 'France'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

print(data)

{'Name': ['Carlos', 'Alan', 'George', 'Héctor'], 'Age': [27, 24, 22, 32], 'Address': ['Mexico', 'India', 'USA', 'France'], 'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}


Usando la librería **Pandas** podemos transformar datos en **DataFrames** que son más últiles para Data Science:

In [13]:
df = pd.DataFrame(data)
df

Name  Age Address Qualification
0  Carlos   27  Mexico           Msc
1    Alan   24   India            MA
2  George   22     USA           MCA
3  Héctor   32  France           Phd

Usando **Pandas**, podemos seleccionar columnas específicas:

In [14]:
print(df[['Name', 'Qualification']])

     Name Qualification
0  Carlos           Msc
1    Alan            MA
2  George           MCA
3  Héctor           Phd


## Transformando: List - Numpy array - Pandas DataFrame

Si tenemos una lista, podríamos necesitar hacer operaciones de vectores. Ees más fácil si en vez de lista usamos **Numpy array**:

In [19]:
my_list_Numpy_transformed = np.asarray(my_list)
my_list_Numpy_transformed


array([1, 2, 3, 4, 5])

También podemos transformar una **Python tuple** a una **Numpy Matrix**:

In [20]:
my_tuple = ([1, 3, 9], [8, 2, 6]) 
     
my_tuple_Numpy = np.asarray(my_tuple)  
my_tuple_Numpy

array([[1, 3, 9],
       [8, 2, 6]])

Y podemos también **convertir nuestro Numpy array de regreso a list**:


In [21]:
my_list_again = my_list_Numpy_transformed.tolist()
print(my_list_again)

[1, 2, 3, 4, 5]


Transformamos **Numpy array** a **Pandas Series**

In [28]:
my_list_Pandas = pd.Series(my_list_Numpy_transformed)
my_list_Pandas

0    1
1    2
2    3
3    4
4    5
dtype: int32

Transformando **de regreso de Pandas a Numpy**:

In [29]:
my_list_Numpy_again = np.asarray(my_list_Pandas)
my_list_Numpy_again

array([1, 2, 3, 4, 5])

## 1. Manipulación de String

- Podemos concatenar y repetir strings con los operadores (+) y (*) respectivamente:

In [1]:
my_string = "Hola Mundo!"
print(my_string * 2)     ### Repeated string

print(my_string + " Python es genial!" * 2)     ### Concatena y repite

Hola Mundo!Hola Mundo!
Hola Mundo! Python es genial! Python es genial!


- Podemos revertir un string usando el operador [::-1] 

In [2]:
print(my_string[::-1])

!odnuM aloH


- También podemos revertir listas!

In [4]:
my_list = [1, 2, 3, 4, 5]
print(my_list[::-1])

[5, 4, 3, 2, 1]


- Lo mismo con listas de strings, un traductor de Yoda!

In [7]:
word_list = ["genial", "es", "esto"]
print(' '.join(word_list[::-1]) + "!")

esto es genial!


En el caso anterior usamos "join()" para unir los elementos de la lista con ' ' y añadimos "!"

## 2. Comprensión de Listas

Supongamos que tenemos una función que sirve para elevar un número al cuadrado y sumarle 5

i.e. $f(x) = x^{2} + 5$

In [30]:
def funcion_chafa(x):
    respuesta = x**2 + 5
    return respuesta

Ahora, supngamos que queremos aplicar esta función a todos los números **impares** de una lista:

In [33]:
lista = [1, 2, 3, 4, 5]
print([funcion_chafa(x) for x in lista if x % 2 != 0])

[6, 14, 30]


La **comprensión de listas** funciona del siguiente modo: [expression **for** item **in** list **if** conditional]

De hecho no necesitamos a la *funcion_chafa()*

In [34]:
print([x**2 + 5 for x in lista if x % 2 != 0])

[6, 14, 30]


## 3. Lambda & Map

Lambda es un poco complicado y raro, pero es muy conveniente una vez que le entiendes

Basicamente, lambda es una pequeña, anónima función. Por qué anónima? Simplemente porque las Lambdas se usan para hacer pequeñas / simples operaciones que no requieren definir una función formal como *def mi_funcion(x)*

Volvamos a tomar el ejemplo de $f(x) = x^{2}+5$, usando Lambdas podemos escribir:

In [35]:
funcion_chafa = (lambda x : x**2 + 5)
print([funcion_chafa(1), funcion_chafa(3), funcion_chafa(5)])

[6, 14, 30]


**¿Por qué usar esta sintaxis tan rara?** Resulta conveniente cuando queremos hacer operaciones simples sin definir formalmente una función. Pensemos en una lista de números, ¿Cómo ordenamos dicha lista en Python? Podemos usar el método *sorted()*

In [36]:
lista = [2, 1, 0, -1, -2]
print(sorted(lista))

[-2, -1, 0, 1, 2]


Funcionó perfectamente, pero, ¿Qué pasa si quisieramos ordenar por los menores cuadrados? POdemos usar Lambdas para ello:

In [37]:
print(sorted(lista, key = lambda x : x**2))

[0, 1, -1, 2, -2]


### Map

Map es simplemente una función que aplica funciones dentro de listas. 

Imaginemos que tenemos dos listas y queremos multiplicar elemento a elemento para obtener una tercera lista. Esto lo podemos lograr con Lambda y Map:

In [39]:
print(list(map(lambda x, y : x * y, [1, 2, 3], [4, 5, 6])))

[4, 10, 18]


Es un equivalente en **Pure Python** al método **numpy.dot** 